logging:
  charset: UTF-8
  level:
    org:
      springframework: WARN

server:
  port: 8189
  servlet:
    context-path: /demo

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '0358'

  flyway:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: '0358'
    enabled: true
    baseline-on-migrate: true
    schemas: public
    default-schema: public
    locations: classpath:db/migration
